### ISSUE TITLE
CWE-284 seems to be missing from the Testcases_Prompt directory

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [s2e-lab/SecurityEval#5]
thank you for the awesome content and fantastic research paper!

[CWE-284](https://cwe.mitre.org/data/definitions/284.html) seems to be missing from the [`Testcases_Prompt`](https://github.com/s2e-lab/SecurityEval/tree/main/Testcases_Prompt) directory as detailed in the [/DataTable.csv](https://github.com/s2e-lab/SecurityEval/blob/main/Result/DataTable.csv).

i couldn't see this mentioned in the paper anywhere, apologies if i am missing something here

thanks!

**Comment by lsiddiqsunny** [comment]
Thank you for this. CWE-284 related prompt has been removed from version 2.
You can find it in the previous version: https://github.com/s2e-lab/SecurityEval/blob/13abc283db1afd5f2a42cbd7c3679eb1853ecb87/dataset.jsonl
